// frise_data.js
// Source UNIQUE des données frise, utilisée par frise.html + annee.html
// Ne pas renommer window.FRISE (les pages l'utilisent)

window.FRISE = [
  {
    year: 2013,
    events: [
      { t: "New génération 0", p: 4 },
      { t: "Inscription de Dude", p: 5 },
      { t: "Inscription de Korben", p: 5 },
      { t: "Dude vs Korben (mini duel)", p: 2 },
      { t: "Korben 1er — 3 mois", p: 3 },
      { t: "Sanji 1er — 1 mois", p: 1 },
      { t: "Aurel-08 1er — 1 mois", p: 1 },
      { t: "Luko vs Seb vs Deidashi vs Aurel-08 (gros duel)", p: 6 },
      { t: "Jordialba vs Aurel-08 (mini duel)", p: 2 },
      { t: "Aurel-08 1er — 1 mois", p: 1 },
      { t: "Monkey D Dragon vs Yassine (duel moyen)", p: 4 },
    ],
  },

  {
    year: 2014,
    events: [
      { t: "Yassine vs Monkey D Dragon vs Jordialba (gros duel)", p: 6 },
      { t: "Inscription de Largo672", p: 5 },
      { t: "Monkey D Dragon 1er — 2 mois", p: 3 },
      { t: "Largo672 vs Maître Gims vs Orsu vs Monkey D Dragon (gros duel)", p: 6 },
      { t: "Largo vs Dude & Korben (mini duel)", p: 2 },
      { t: "Largo672 1er — 32 mois (new premier)", p: 6 },
      { t: "Akai vs Distructeur vs Hyorinmaru (duel moyen)", p: 4 },
      { t: "Inscription de Talk Takashi", p: 5 },
      { t: "Inscription de Josué455 & Djabrail", p: 10 },
      { t: "Akai vs Distructeur vs Hyorinmaru (mini duel)", p: 2 },
      { t: "Inscription de Seka (mini)", p: 2 },
      { t: "Seka vs Josué455 (mini duel)", p: 2 },
    ],
  },

  {
    year: 2015,
    events: [
      { t: "Seka vs Djabrail (mini duel)", p: 2 },
      { t: "Inscription de Cahincaha", p: 5 },
      { t: "New génération 1", p: 4 },
      { t: "Josué455 vs Ronaldo651 (mini duel)", p: 2 },
      { t: "Cahincaha vs Ronaldo651 (mini duel)", p: 2 },
      { t: "Josué455 vs Seka (mini duel)", p: 2 },
      { t: "Cahincaha vs Djabrail (gros duel)", p: 6 },
      { t: "Largo672 atteint le niveau 100", p: 5 },
      { t: "Inscription de Hoopa", p: 5 },
      { t: "Inscription de Francoeur", p: 5 },
      { t: "Suppression de Cahincaha", p: -3 },
    ],
  },

  {
    year: 2016,
    events: [
      { t: "Inscription d'Abelard", p: 5 },
      { t: "Largo672 vs Djabrail (duel moyen)", p: 4 },
      { t: "Abelard vs Francoeur (mini duel)", p: 2 },
      { t: "New génération 2", p: 4 },
      { t: "Talk Takashi vs Francoeur (mini duel)", p: 2 },
      { t: "Swaga976 vs Seka (duel moyen)", p: 4 },
      { t: "Djabrail atteint le niveau 100", p: 5 },
      { t: "Josué455 atteint le niveau 100", p: 5 },
      { t: "Talk Takashi vs Abelard (gros duel)", p: 6 },
      { t: "Josué455 1er — 6 mois", p: 4 },
    ],
  },

  {
    year: 2017,
    events: [
      { t: "Abelard + Talk Takashi atteignent le niveau 100", p: 10 },
      { t: "Abelard vs Talk Takashi (gros duel)", p: 6 },
      { t: "Abelard vs Josué455 (gros duel)", p: 6 },
      { t: "Abelard 1er — 1 mois", p: 1 },
      { t: "Duel de 1er", p: 3 },
      { t: "Inscription d'Alex.c2109", p: 5 },
      { t: "Inscription de Golder", p: 5 },
      { t: "Alex.c2109 vs Golder (duel moyen)", p: 4 },
      { t: "Josué455 atteint 100K", p: 5 },
      { t: "Abelard atteint 100K", p: 5 },
      { t: "Talk Takashi atteint 100K", p: 5 },
      { t: "Talk Takashi vs Abelard (duel moyen)", p: 4 },
    ],
  },

  {
    year: 2018,
    events: [
      { t: "Talk Takashi vs Josué455 (mini duel)", p: 2 },
      { t: "Talk Takashi 1er (new premier)", p: 6 },
      { t: "Inscription d'Esdras950", p: 5 },
      { t: "Inscription d'Alexis279", p: 5 },
      { t: "New génération 3", p: 4 },
      { t: "Inscription de Unit", p: 5 },
      { t: "Golder vs Francoeur (mini duel)", p: 2 },
      { t: "Unit vs Esdras950 (mini duel)", p: 2 },
      { t: "Golder vs Alex.c2109 (duel moyen)", p: 4 },
      { t: "Talk Takashi atteint 200K", p: 5 },
      { t: "Dude atteint le niveau 100", p: 5 },
      { t: "Korben atteint le niveau 100", p: 5 },
    ],
  },

  {
    year: 2019,
    events: [
      { t: "Inscription de Lumia + Athèna + Acno", p: 15 },
      { t: "Duel (Alex.c2109 + Golder + Francoeur + Unit)", p: 4 },
      { t: "Francoeur vs Alex.c2109 (gros duel)", p: 6 },
      { t: "Inscription de Jordan.io + Blackout + Pingu", p: 15 },
      { t: "Hoopa vs Alexis279 (mini duel)", p: 2 },
      { t: "Inscription de Marcosino (mini)", p: 2 },
      { t: "Alex.c2109 + Francoeur atteignent le niveau 100", p: 10 },
      { t: "Hoopa atteint le niveau 100", p: 5 },
      { t: "Hoopa vs Francoeur (duel moyen)", p: 4 },
      { t: "Hoopa vs Alex.c2109 (duel moyen)", p: 4 },
      { t: "Talk Takashi atteint 300K", p: 5 },
      { t: "Hoopa atteint 100K", p: 5 },
      { t: "Hoopa vs Abelard (mini duel)", p: 2 },
      { t: "Gros bot", p: -4 },
      { t: "Francoeur atteint 100K", p: 5 },
      { t: "Talk Takashi atteint 400K", p: 5 },
      { t: "Alex.c2109 vs Abelard (mini duel)", p: 2 },
    ],
  },

  {
    year: 2020,
    events: [
      { t: "Unit vs Esdras950 (duel moyen)", p: 4 },
      { t: "Inscription de Cirpacha", p: 5 },
      { t: "New génération 4", p: 4 },
      { t: "Alexis279 vs Esdras950 vs Unit vs Golder (gros duel)", p: 6 },
      { t: "Alexis279 + Golder atteignent le niveau 100", p: 10 },
      { t: "Alex.c2109 atteint 200K", p: 5 },
      { t: "Jordan.io vs Golder vs Unit vs Esdras950 (gros duel)", p: 6 },
      { t: "Jordan.io + Esdras950 + Unit atteignent le niveau 100", p: 15 },
      { t: "Inscription de Tellor", p: 5 },
      { t: "Cirpacha atteint le niveau 100", p: 5 },
      { t: "Alexis279 atteint 100K", p: 5 },
      { t: "Cirpacha vs Esdras950 vs Golder vs Jordan.io (gros duel)", p: 6 },
      { t: "Inscription de TheGladiator", p: 5 },
      { t: "Inscription de Bételgeuse & Aldébaran", p: 10 },
      { t: "Bételgeuse vs Aldébaran (mini duel)", p: 2 },
      { t: "Tellor vs TheGladiator (duel moyen)", p: 4 },
      { t: "Talk Takashi atteint 500K", p: 5 },
      { t: "Francoeur vs Abelard (mini duel)", p: 2 },
      { t: "TheGladiator atteint le niveau 100", p: 5 },
      { t: "TheGladiator vs Cirpacha + Esdras950 + Jordan.io (gros duel)", p: 6 },
      { t: "TheGladiator atteint 100K", p: 5 },
      { t: "Talk Takashi atteint 600K", p: 5 },
      { t: "Francoeur atteint 200K", p: 5 },
      { t: "TheGladiator vs Alexis279 (gros duel)", p: 6 },
      { t: "Cirpacha vs Esdras950 (duel moyen)", p: 4 },
      { t: "Jordan.io atteint 100K", p: 5 },
      { t: "TheGladiator atteint 200K", p: 5 },
      { t: "Talk Takashi atteint 700K", p: 5 },
      { t: "Alex.c2109 atteint 300K", p: 5 },
    ],
  },

  {
    year: 2021,
    events: [
      { t: "Inscription de Venom_", p: 5 },
      { t: "TheGladiator vs Francoeur (gros duel)", p: 6 },
      { t: "Cirpacha atteint 100K", p: 5 },
      { t: "Talk Takashi atteint 800K", p: 5 },
      { t: "TheGladiator atteint 300K", p: 5 },
      { t: "Talk Takashi atteint 900K", p: 5 },
      { t: "Francoeur atteint 300K", p: 5 },
    ],
  },

  {
    year: 2022,
    events: [
      { t: "Esdras950 atteint 100K", p: 5 },
      { t: "New génération 5", p: 4 },
      { t: "Francoeur vs Alex.c2109 (gros duel)", p: 6 },
      { t: "Inscription de UY-Scuty", p: 5 },
      { t: "Talk Takashi atteint 1M", p: 7 },
      { t: "Jordan.io vs Josué455 (duel moyen)", p: 4 },
      { t: "Abelard atteint 200K", p: 5 },
      { t: "Blackout vs Athèna vs Bételgeuse vs Aldébaran vs Redbot (duel moyen)", p: 4 },
      { t: "UY-Scuty vs Acno (mini duel)", p: 2 },
      { t: "Redbot atteint le niveau 100", p: 5 },
      { t: "Mini bot", p: -2 },
    ],
  },

  {
    year: 2023,
    events: [
      { t: "Alex.c2109 atteint 400K", p: 5 },
      { t: "Inscription de Cahincaha2 + Houka", p: 10 },
      { t: "Jordan.io atteint 200K", p: 5 },
      { t: "Talk Takashi atteint 1M1", p: 5 },
      { t: "Francoeur atteint 400K", p: 5 },
    ],
  },

  {
    year: 2024,
    events: [
      { t: "Inscription de Justice-", p: 5 },
      { t: "Alex.c2109 atteint 500K", p: 5 },
      { t: "Pingu vs Justice- (duel moyen)", p: 4 },
      { t: "Inscription de Napoléon.1er", p: 5 },
      { t: "Pingu atteint le niveau 100", p: 5 },
      { t: "Lumia atteint 100K", p: 5 },
      { t: "Alex.c2109 atteint 600K", p: 5 },
    ],
  },

  {
    year: 2025,
    events: [
      { t: "Alex.c2109 atteint 700K", p: 5 },
      { t: "Talk Takashi atteint 1M2", p: 5 },
      { t: "Inscription de Polyy", p: 5 },
      { t: "Inscription de Venom2", p: 5 },
    ],
  },

  {
    year: 2026,
    events: [
      { t: "Dude atteint 100K", p: 5 },
      { t: "Alex.c2109 atteint 800K", p: 5 },
      { t: "Inscription de Ko0pa + Clovis1er + LargoJunior", p: 15 },
      { t: "Justice- vs Ko0pa (mini duel)", p: 2 },
      { t: "LargoJunior vs Polyy (mini duel)", p: 2 },
      { t: "Ko0pa atteint le niveau 100", p: 5 },

      // AJOUTS demandés
      { t: "TheGladiator atteint 400K", p: 5 },
      { t: "Ko0pa et Unit atteignent 100K", p: 10 },
      { t: "Duel Unit vs Ko0pa", p: 2 },
      { t: "Duel Houka vs Justice-", p: 4 },
      { t: "Ko0pa atteint 100K", p: 5 },
      { t: "Houka, Justice-, LargoJunior & Blackout atteignent le niveau 100", p: 20 },
      { t: "Aldébaran, Bételgeuse, UY-Scuty atteignent le niveau 100", p: 15 },
    ],
  },
];
