// gangdata.js
// members = [{nom, xp?, karas?, avatar?}]
// Si xp/karas/avatar manquent -> on tentera de récupérer via data.js (joueurs) dans les pages.

const gangsData = [
  {
    name: "x934 GANGGG",
    img: "avatar/gang2.png",
    classement: "—",
    rang: "—",
    creation: "—",
    chefLabel: "Élite",
    chefValue: "x934, Wawan, Joqueur, nadal51",
    recrutement: "—",
    trophees: "—",
    karas: null,
    members: [
      { nom: "x934", xp: 7464, karas: 3543, avatar: "avatar/105.jpg" },
      { nom: "wawan5871", xp: 350, karas: 413, avatar: "avatar/106.jpg" },
      { nom: "x934-2", xp: 132, karas: 186, avatar: "avatar/123.jpg" },
      { nom: "Joqueur", xp: 1372, karas: 416, avatar: "avatar/107.jpg" },
      { nom: "nadal51", xp: 7900, karas: 17819, avatar: "avatar/103.jpg" },
      { nom: "ronaldo.siuuu", xp: 14454, karas: 66408, avatar: "avatar/102.jpg" },
      { nom: "altesse10", xp: 3150, karas: 914, avatar: "avatar/101.jpg" },
      { nom: "shakadai", xp: 3678, karas: 10207, avatar: "avatar/100.jpg" },
      { nom: "harris100", xp: 10008, karas: 1522, avatar: "avatar/108.jpg" },
      { nom: "nadal50", xp: 6768, karas: 5982, avatar: "avatar/108.jpg" },
    ],
  },

  {
    name: "Athèna Gangster",
    img: "avatar/gang1.jpg",
    classement: "—",
    rang: "—",
    creation: "13-04-2023",
    chefLabel: "Chef du gang",
    chefValue: "Talk Takashi",
    recrutement: "Limité",
    trophees: "66",
    karas: null,
    members: [
      { nom: "Talk Takashi" },
      { nom: "Venom_", avatar: "avatar/21.jpg" },
      { nom: "lumia" },
      { nom: "Unit" },
      { nom: "redbot" },
      { nom: "Jordan.io" },
      { nom: "Alexis279" },
    ],
  },

  {
    name: "Los Pollos Gangsta",
    img: "avatar/gang3.png",
    classement: "—",
    rang: "—",
    creation: "—",
    chefLabel: "Chef du gang",
    chefValue: "alex.c2109",
    recrutement: "—",
    trophees: "—",
    karas: null,
    members: [
      { nom: "alex.c2109" },
      { nom: "TheGladiator" },
      { nom: "Pingu" },
      { nom: "Abelard" },
      { nom: "hoopa" },
      { nom: "Tellor" },
      { nom: "Golder" },
      { nom: "cirpacha" },
    ],
  },

  {
    name: "Tribu Esdrasso",
    img: "avatar/gang4.png",
    classement: "—",
    rang: "—",
    creation: "—",
    chefLabel: "Chef du gang",
    chefValue: "Esdras950",
    recrutement: "—",
    trophees: "—",
    karas: null,
    members: [
      { nom: "Esdras950" },
      { nom: "ariel005", xp: 26844, karas: 128092, avatar: "avatar/140.jpg" },
      { nom: "tidadouslip", xp: 26846, karas: 143834, avatar: "avatar/106.jpg" },
      { nom: "Esdrasso", xp: 746, karas: 495, avatar: "avatar/104.jpg" },
      { nom: "esdrasnoob", xp: 4, karas: 4, avatar: "avatar/111.jpg" },
      { nom: "Esdras270", xp: 116, karas: 50, avatar: "avatar/120.jpg" },
      { nom: "Esdras512", xp: 56, karas: 29, avatar: "avatar/121.jpg" },
      { nom: "francoeur" },
      { nom: "josué455" },
      { nom: "djabrail" },
      { nom: "multijoueur", xp: 6184, karas: 233, avatar: "avatar/124.jpg" },
      { nom: "ESC2019", xp: 10386, karas: 19836, avatar: "avatar/82.jpg" },
    ],
  },

  {
    name: "Team Power",
    img: "avatar/gang5.png",
    classement: "—",
    rang: "—",
    creation: "—",
    chefLabel: "Chef du gang",
    chefValue: "—",
    recrutement: "—",
    trophees: "—",
    karas: null,
    members: [
      { nom: "azedine1974", xp: 2592, karas: 55, avatar: "avatar/108.jpg" },
      { nom: "YTB", xp: 5162, karas: 41, avatar: "avatar/109.jpg" },
      { nom: "HARSON", xp: 774, karas: 1303, avatar: "avatar/114.jpg" },
    ],
  },

  {
    name: "Team Esdrax",
    img: "avatar/gang10.png",
    classement: "—",
    rang: "—",
    creation: "—",
    chefLabel: "Chef du gang",
    chefValue: "—",
    recrutement: "—",
    trophees: "—",
    karas: null,
    members: [
      { nom: "esdrax789", xp: 1092, karas: 2031, avatar: "avatar/114.jpg" },
      { nom: "Esdraxkenny", xp: 192, karas: 282, avatar: "avatar/115.jpg" },
      { nom: "Esdraxjosue", xp: 360, karas: 644, avatar: "avatar/116.jpg" },
      { nom: "Zecrom.27", xp: 21672, karas: 11432, avatar: "avatar/118.jpg" },
      { nom: "luanbau", xp: 25048, karas: 139783, avatar: "avatar/119.jpg" },
    ],
  },

  {
    name: "Le gang des gangsters",
    img: "avatar/gang8.jpg",
    classement: "—",
    rang: "—",
    creation: "—",
    chefLabel: "Chef du gang",
    chefValue: "—",
    recrutement: "—",
    trophees: "—",
    karas: null,
    members: [
      { nom: "joann", xp: 7832, karas: 2111, avatar: "avatar/34.jpg" },
      { nom: "albanisuf1", xp: 11850, karas: 4214, avatar: "avatar/108.jpg" },
      { nom: "bojetoDU95", xp: 3120, karas: 894, avatar: "avatar/118.jpg" },
      { nom: "ambdoul-lathuf", xp: 9456, karas: 22872, avatar: "avatar/40.jpg" },
      { nom: "MASTERMAGIC91", xp: 2398, karas: 3292, avatar: "avatar/124.jpg" },
      { nom: "MAGIC91", xp: 2832, karas: 891, avatar: "avatar/102.jpg" },
      { nom: "Angel13", xp: 1970, karas: 379, avatar: "avatar/125.jpg" },
      { nom: "akramnaji123", xp: 1234, karas: 1729, avatar: "avatar/126.jpg" },
      { nom: "Xerocs77", xp: 3160, karas: 6684, avatar: "avatar/127.jpg" },
      { nom: "Youyoudu71", xp: 1248, karas: 1803, avatar: "avatar/126.jpg" },
    ],
  },

  {
    name: "Mois Républicains",
    img: "avatar/gang6.png",
    classement: "—",
    rang: "—",
    creation: "—",
    chefLabel: "Chef du gang",
    chefValue: "—",
    recrutement: "—",
    trophees: "—",
    karas: null,
    members: [
      { nom: "Vendémiaire", xp: 4, karas: 4, avatar: "avatar/123.jpg" },
      { nom: "Pluviôse", xp: 4, karas: 4, avatar: "avatar/123.jpg" },
      { nom: "Brumaire", xp: 4, karas: 4, avatar: "avatar/123.jpg" },

      { nom: "Messidor", xp: 4, karas: 4, avatar: "avatar/116.jpg" },
      { nom: "Frimaire", xp: 4, karas: 4, avatar: "avatar/116.jpg" },
      { nom: "Ventôse", xp: 4, karas: 4, avatar: "avatar/116.jpg" },

      { nom: "Nivôse", xp: 4, karas: 4, avatar: "avatar/111.jpg" },
      { nom: "Germinal", xp: 4, karas: 4, avatar: "avatar/111.jpg" },
      { nom: "Floréal", xp: 4, karas: 4, avatar: "avatar/111.jpg" },

      { nom: "Prairial", xp: 4, karas: 4, avatar: "avatar/115.jpg" },
      { nom: "Fructidor", xp: 4, karas: 4, avatar: "avatar/115.jpg" },
      { nom: "Thermidor", xp: 4, karas: 4, avatar: "avatar/115.jpg" },
    ],
  },

  {
    name: "Admin",
    img: "avatar/gang7.jpg",
    classement: "—",
    rang: "—",
    creation: "—",
    chefLabel: "Chef du gang",
    chefValue: "—",
    recrutement: "—",
    trophees: "—",
    karas: null,
    members: [
      { nom: "dude", xp: 100258, karas: 607188, avatar: "avatar/37.jpg" },
      { nom: "Korben", xp: 92406, karas: 406000, avatar: "avatar/38.jpg" },
    ],
  },

  {
    name: "Legend",
    img: "avatar/gang9.png",
    classement: "—",
    rang: "—",
    creation: "—",
    chefLabel: "Chef du gang",
    chefValue: "—",
    recrutement: "—",
    trophees: "—",
    karas: null,
    members: [
  { nom: "Largo672" },

  { nom: "Largo675", xp: 0, karas: 0, avatar: "avatar/123.jpg" },
  { nom: "largo678", xp: 50, karas: 24, avatar: "avatar/121.jpg" },
  { nom: "largo679", xp: 0, karas: 0, avatar: "avatar/116.jpg" },
  { nom: "Largo674", xp: 6, karas: 6, avatar: "avatar/111.jpg" },
  { nom: "Largo673", xp: 562, karas: 1068, avatar: "avatar/111.jpg" },
  { nom: "largo671", xp: 34, karas: 8, avatar: "avatar/132.jpg" },
  { nom: "Largo670", xp: 1618, karas: 547, avatar: "avatar/133.jpg" },
  { nom: "Largo1", xp: 102, karas: 156, avatar: "avatar/111.jpg" },
  { nom: "largo", xp: 12, karas: 17, avatar: "avatar/115.jpg" },

  { nom: "obito45", xp: 6532, karas: 7478, avatar: "avatar/153.jpg" },
  { nom: "bob", xp: 14596, karas: 68551, avatar: "avatar/114.jpg" },
  { nom: "seka" },
  { nom: "marcosino" },
  { nom: "cahincaha", xp: 42000, karas: 305789, avatar: "avatar/141.jpg" },
],
  },

  {
    name: "40k Gang",
    img: "avatar/gang9.png",
    classement: "—",
    rang: "—",
    creation: "—",
    chefLabel: "Chef du gang",
    chefValue: "—",
    recrutement: "—",
    trophees: "—",
    karas: null,
    members: [
      { nom: "cahincaha" },
      { nom: "Houka" },
      { nom: "Justice-" },
      { nom: "UY-Scuty" },
      { nom: "Bételgeuse" },
      { nom: "Aldébaran" },
      { nom: "blackout" },
      { nom: "Athèna" },
      { nom: "acno" },
      { nom: "Napoléon.1er" },
      { nom: "venom2" },
      { nom: "Clovis1er" },
      { nom: "Polyy" },
      { nom: "LargoJunior" },
    ],
  },
];